# Generated by Django 2.1.8 on 2020-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('my_school', models.ForeignKey(on_delete=None, to='relation.School')),
            ],
        ),
    ]
