if exists (select * from sysobjects where id = OBJECT_ID('[provinces]') and OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [provinces]

CREATE TABLE [provinces] (
[id] [int]  NOT NULL,
[provinceid] [nvarchar]  (50) NOT NULL,
[province] [nvarchar]  (50) NOT NULL)

INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 1,N'110000',N'北京市')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 2,N'120000',N'天津市')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 3,N'130000',N'河北省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 4,N'140000',N'山西省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 5,N'150000',N'内蒙古自治区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 6,N'210000',N'辽宁省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 7,N'220000',N'吉林省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 8,N'230000',N'黑龙江省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 9,N'310000',N'上海市')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 10,N'320000',N'江苏省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 11,N'330000',N'浙江省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 12,N'340000',N'安徽省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 13,N'350000',N'福建省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 14,N'360000',N'江西省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 15,N'370000',N'山东省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 16,N'410000',N'河南省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 17,N'420000',N'湖北省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 18,N'430000',N'湖南省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 19,N'440000',N'广东省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 20,N'450000',N'广西壮族自治区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 21,N'460000',N'海南省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 22,N'500000',N'重庆市')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 23,N'510000',N'四川省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 24,N'520000',N'贵州省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 25,N'530000',N'云南省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 26,N'540000',N'西藏自治区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 27,N'610000',N'陕西省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 28,N'620000',N'甘肃省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 29,N'630000',N'青海省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 30,N'640000',N'宁夏回族自治区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 31,N'650000',N'新疆维吾尔自治区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 32,N'710000',N'台湾省')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 33,N'810000',N'香港特别行政区')
INSERT [provinces] ([id],[provinceid],[province]) VALUES ( 34,N'820000',N'澳门特别行政区')
